[package]
name = "bevy_sokoban"
version = "0.1.0"
authors = ["Dima Lazarev <dmitry.lazarev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
 bevy = { git = "https://github.com/bevyengine/bevy" }